### ISSUE TITLE
Unwanted change on navbar

### ISSUE THREAD

**Issue by helloadib** [edrisranjbar/sammakquran#10]
I start with an example to make this issue simple:

When we are in https://sammakqoran.com/video/, the selected item on the bottom navbar is Videos (Desired outcome.)
When we press the "View More" button, the URL changes to something like this: https://sammakqoran.com/video/?pageNumber=2, which makes the default item of the bottom navbar (Home) to be selected (Undesired outcome.)
In both scenarios the selected item of the navbar must be the item that represents that post type (Videos in this example.)
Please fix this.

Thanks Manks.

**Comment by edrisranjbar** [comment]
Thanks for notifying me about this issue, I fix it.
