### ISSUE TITLE
Display Playlists in Category page

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/sammakquran#12]
As you are already informed; we want to see playlists within a single category being listed like we are listing Categories in home page.

let me know when the front-end side of this issue is done so that i can proceed and write back-end part of the issue. **Thanks**

**Comment by helloadib** [comment]
@edrisranjbar Hi
I did the front-end part of it.
It's on my repo (the one that only contains front-end code.)

Thank you.

**Comment by edrisranjbar** [comment]
Thanks @helloadib,
**I guess these files should be updated in back-end:**
- [ ] Category page
- [ ] sliders.js
- [ ] update theme version to clear cache

**Comment by edrisranjbar** [comment]
This is still in progress. I'm having problem with filtering only playlists that have posts in certain category. It's late, tommorow will be fixed Insha-Allah.

**Comment by edrisranjbar** [comment]
Thanks to adib we found new sub-issues for this issue to be solved.
TODO:
- [ ] link badges to actual playlist
- [ ] show all playlists of particular category whether or not it's been loaded completely or not (do not consider the pagination stuff...)

**Comment by edrisranjbar** [comment]
Thank you @helloadib for letting me be aware of this issue. I'm working on _several projects_ at the same time and sometimes this kind of issue happen. Anyway...
I fixed both of the problems, and I tested in `Localhost` and `Production`; but I want you to take a look and let me know if we can close this issue or not.

**Thanks again.**

**Comment by helloadib** [comment]
@edrisranjbar Yo BROOOOOO!
IT'S LOOKING GOOD!
THANKS!
