### ISSUE TITLE
Display Subcategories of a category

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/sammakquran#20]
we need to support hierarchical category for posts. for example we have `اناشید` and then `اناشید صوتی` and `اناشید تصویری` inside that category. and we also should categories based on singer. so that `عبدالستار سماک` and `عفاسی` are separated.
I'm not sure about the structure they want. but we should figure it out somehow that can be applied for different use cases.

## TODO
Here are some steps to take in order to fix this issue:
- [x] Limit categories displayed in `index.php` to only the `top level` categories
- [x] in `category.php` in addition to playlists, we should display `sub-categories` of that particular category

**Comment by helloadib** [comment]
@edrisranjbar Yo bro!
The front-end part is done.
Don't forget to replace `sliders.js`, `styles.css`, and `medium-device.css` entirely (includes other updates that need to be updated on the website.)

P.S. I've changed my website URL in `index.php` in the main branch, could you please upload it to the website? Thanks.
