### ISSUE TITLE
Display audio duration in Front-End

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/sammakquran#21]
we should display audio duration via `js` code in front-end.

**Comment by helloadib** [comment]
@edrisranjbar MEGRE BABE!
please,
thanks,

**Comment by edrisranjbar** [comment]
we are getting a Error and the duration label contains **NaN:NaN:NaN** .
**The error message that we are getting in the console.**
```
Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at HTMLInputElement.seek (audio-player.js?v=2:52:21)
seek @ audio-player.js?v=2:52
```

**Comment by edrisranjbar** [comment]
we need a better way to make sure were getting the audio duration after metadata loads. I think it must be an `async` method.

@helloadib

**Comment by edrisranjbar** [comment]
I think its finally done!
