### ISSUE TITLE
use pagination instead of load more

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/sammakquran#24]
we need pagination because, count of posts in each page can be a lot.

**Comment by helloadib** [comment]
Front-end is done:

- [ ] Update `main.js`
- [ ] Update `style.css`
- [ ] Change button container to a form
- [ ] Add new buttons and select menu
- [ ] Make select menu submit the form on change

**Comment by edrisranjbar** [comment]
@helloadib 

function goToLink(thisElem) {
  let url = new URL(window.location.href);
  let search_params = url.searchParams;
  search_params.set('pageNumber', thisElem.value);
  window.location.href = url;
}
