### ISSUE TITLE
Load more must scroll to the first newly loaded item

### ISSUE THREAD

**Issue by helloadib** [edrisranjbar/sammakquran#9]
When we press load more, the window must be scrolled to the first newly loaded item on the page.
I will do the front-end part of it.
@edrisranjbar please give each post an ID with this pattern:
p1, p2, p3, etc.

Thank you.

**Comment by helloadib** [comment]
@edrisranjbar 
Yo bro, the front-end part is done.
Please add IDs and also give the "View More" button an onclick function named `getPostCardsCount()`.

Thanks in advance.

**Comment by edrisranjbar** [comment]
Done bro, Thanks
